name: Auto commit

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *" # Run every 5 minutes

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{ github.ref }}"

      - uses: actions/checkout@v3      
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify last update
        run: |
          d=$(date '+%Y-%m-%dT%H:%M:%SZ')
          echo $d > LAST_UPDATED

      - name: Configure Git
        run: |
          git config --local user.email "purvapatel4725@gmail.com"
          git config --local user.name "Purvapatel4725"

      - name: Stash uncommitted changes
        run: git stash || echo "No changes to stash"

      - name: Pull latest changes
        run: git pull origin main --rebase

      - name: Apply stashed changes
        run: git stash pop || echo "No stashed changes to apply"

      - name: Commit changes
        run: |
          git add -A
          
          arr=("chore(bot): 😂 auto commit" "melon(bot): 😱 auto commit" "melon(bot): 👿 auto commit" "melon(bot): 🫠 auto commit" "melon(bot): 🤧 auto commit" "melon(bot): 💀 auto commit" "melon(bot): 😭 auto commit" "melon(bot): 🤖 auto commit" "melon(bot): 😅 auto commit" "melon(bot): 👻 auto commit")
          rand=$((RANDOM % ${#arr[@]}))
          
          git commit -m "${arr[$rand]}"

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
